### ISSUE TITLE
Adding class, name has white space in it

### ISSUE THREAD

**Issue by miguelTowsonCompSci** [JalIrani/tomsoft#3]
that the add/remove classes code is functional

**Comment by nlicci1** [comment]
There is a bug where you add a new class to the DB and the class name has white space in it (more than 1 token) it will not reference the full name that the user entered. It will only reference the first token as the class name. 

The issue with that is when you try to make that class a "current" class it will not query the proper class name in the DB thus not updating the "current" column in the DB.

**Comment by kmoo** [comment]
ಠ_ಠ

**Comment by nlicci1** [comment]
Deal w/ it

**Comment by kmoo** [comment]
K.

ಠ益ಠ

**Comment by nlicci1** [comment]
¯_(ツ)_/¯ idk what to tell you bro
