### ISSUE TITLE
After new student "submits" info, TomSoft closes

### ISSUE THREAD

**Issue by richard-frink** [JalIrani/tomsoft#32]
Should (probably) go back to the main page afterwards

**Comment by nlicci1** [comment]
TomSoft does not close when a student submits a file it reopens the submit a file window. What if more than one student needs to submit a file (or one student submits multiple files)? This is technically an enhancement not a bug and I do not see how that would improve the software.

In my own opinion I see more advantages to how it is currently done. We are going to show v0.6 to our client on 4/10. If our client doesn't like it we can change it.

I'm closing this issue for now.
