### ISSUE TITLE
Student cannot submit after certain administrator actions are taken in Master

### ISSUE THREAD

**Issue by cknoll1** [JalIrani/tomsoft#41]
Bug discovered in master. Unknown if it persists in Dev.
To Repo this bug:
Login to administrator.
Open the settings panel.
Open the add/remove class dialog.
Save or Cancel out.
From the main screen, clicking on student no longer displays a submit button.

**Comment by phickm1** [comment]
Successfully repoed on second computer

**Comment by miguelTowsonCompSci** [comment]
Please include recreation steps.

**Comment by cknoll1** [comment]
Check the notes. They're in the notes.

On 4/19/2015 9:19 AM, miguelTowsonCompSci wrote:

> Please include recreation steps.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/JalIrani/tomsoft/issues/41#issuecomment-94276391.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
