### ISSUE TITLE
File Button Leads to Infinite Instances of OLI

### ISSUE THREAD

**Issue by phickm1** [JalIrani/tomsoft#50]
Version: Develop Branch as of 4/21

In any of the printer "build creators" under "file" and then "reports": after you open "reports" you can then hit close to close it, and it will open another instance of OLI

Steps to repo:
Administrator >> any printer button (zcorp, etc) >> file >> reports >> close
The steps file >> reports >> close can be repeated infinitely.

This bug was not using the dynamic database script.

It seems to work in any screen in which the "file" button is available to the user.

**Comment by phickm1** [comment]
On the bright side, hitting the X button in the top right closes all of them at once.

**Comment by phickm1** [comment]
Oops, version is 0.6

**Comment by nlicci1** [comment]
Fixed it getting ready to merge into develop2
