### ISSUE TITLE
Can't add TUID / user IDs that start with a '0' (on branch "dev/login")

### ISSUE THREAD

**Issue by nlicci1** [JalIrani/tomsoft#57]
This screen shot of the software running in debug mode will literally explain it all (Fix is we have to make this a String in the DB?):

https://cloud.githubusercontent.com/assets/11018482/7342472/bf999c50-ec82-11e4-8560-39e0f530403.jpg

**Comment by nlicci1** [comment]
Luke if Mike is available tomorrow he should be able to help you. I can assist as well.

**Comment by kmoo** [comment]
This has to be stored as a string. Integers/numbers cannot start with a "0," only strings can.
