### ISSUE TITLE
Bug where exiting out of or submitting "new student" and "update student" pages sends you into administrator menu. Details in description...

### ISSUE THREAD

**Issue by richard-frink** [JalIrani/tomsoft#73]
This is the most recent version of the develop2 branch. exact steps to replicate code:
1.Start OLI
2.select "new student"
3.Select Cancel
4.Login as admin
5.Go to (approve/reject file) or (enter build) or (reports) or (settings) //aka any option in the admin menu works
6.go back a screen
7.logout of admin
8.select "new student"
9.select cancel
admin menu opens up.

This is very unlikely to happen, but it definitely can happen, so you can probably ignore this one, but i wanted to put it out there.

**Comment by nlicci1** [comment]
I reproduced these steps and I was not logged into admin. This may have been fixed when administrative login was finished.

**Comment by kmoo** [comment]
closed by me and @nlicci1
