### ISSUE TITLE
UI problem with User id length warning

### ISSUE THREAD

**Issue by cknoll1** [JalIrani/tomsoft#81]
On current main page, the warning falls under the login and add user buttons.
The warning text also persists after login as an admin, existing over the top two buttons.
I'd include images, but it's simple to repo:
1: attempt to login as a student with number of entered numbers =/= 7
2: login as admin.

Also the image uploading doesn't work.

**Comment by kmoo** [comment]
Which branch? Update in the comment

**Comment by cknoll1** [comment]
dev2, but as you noted in an issue you opened the admin problem persists
